apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: gagandeep39/blog-event-bus
          resources:
            limits:
              memory: '128Mi'
              cpu: '250m'
          env:
            - name: POSTS_SERVICE
              value: posts-clusterip-srv
            - name: COMMENT_SERVICE
              value: comment-serv
            - name: MODERATION_SERVICE
              value: moderation-serv
            - name: QUERY_SERVICE
              value: query-serv

---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-serv
spec:
  selector:
    app: event-bus
  ports:
    - port: 7000
      targetPort: 7000
      name: event-bus-port
      protocol: TCP
