apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  # Actual pod description
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts
        image: gagandeep39/blog-posts-service
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
